spring:
  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: 158.178.246.204
      port: 3009
      username: default
      password: CcLqI7gBESGsGfd3wZ7WJwI20kM1AOeMxtVXRg7XfN5QmB2imDNI5gDAIqf8qQzn
  application:
    name: productservice
  datasource: #CONFIG POSTGRES CONNECTION
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://158.178.246.204:3006/batch16_product_management
    username: postgres
    password: EzeX24QUrUpUU3MabkzocHHRcIZ8cxiaDbbftRI5JQgiF4dPLGoDjyPQp9wK7mCT
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #ngerapiin query sql di console
        show_sql: true #munculin query sql di console
server:
  port: 8082
  servlet:
    context-path: /product

kafka:
  bootstrap-servers: 158.178.246.204:3021

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true