spring:
  application:
    name: productservice
  datasource: #CONFIG POSTGRES CONNECTION
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_batch_16
    username: postgres
    password: dimas
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #ngerapiin query sql di console
        show_sql: true #munculin query sql di console
server:
  port: 8082
  servlet:
    context-path: /product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/